---
- name: testing
  hosts: web
  tasks:
    - name: Install
      yum:
        name: httpd
        state: present
      notify: request httpd
  handlers:
    - name: restarted httpd
      service:
         name: httpd
         state: restarted
