---
- name: Intranet Website
  hosts: web
  tasks:
    - name: Install latest version of httpd and fiewall
      yum:
        name:
          - httpd
          - firewalld
        state: latest

    - name: Test html page is added
      copy:
        src: /root/index.html
        dest: /var/www/html/

    - name: Firewall running & enabled
      service:
        name: firewalld
        enabled: true
        state: started

    - name: Firewall permit access to httpd
      firewalld:
        service: http
        permanent: true
        immediate: yes
        state: enabled
        
    - name: httpd enabled and running
      service:
        name: httpd
        enabled: true
        state: started
