---
- name: gameplay
  hosts: all
  tasks:
  - name: creating user
    user:
      name: vigy
      state: present
    tags: creating for global
  - name: installing package
    yum:
      name: httpd
      state: present
